---
openapi: 3.0.3
info:
 title: user-profile-avatar internal service
 version: 1.0.0
servers:
 - url: "http://onecx-user-profile-avatar:8080"
tags:
 - name: avatarInternal
paths:
  /internal/avatar/{userId}:
   post:
    security:
     - oauth2: [ ocx-up:all, ocx-up:write ]
    tags:
     - avatarInternal
    description: Upload Images
    parameters:
     - in: header
       name: Content-Length
       required: true
       schema:
        minimum: 1
        maximum: 110000
        type: integer
     - name: userId
       in: path
       required: true
       schema:
        type: string
     - name: refType
       in: query
       required: true
       schema:
        $ref: "#/components/schemas/RefType"
    operationId: uploadImage
    requestBody:
     required: true
     content:
      image/*:
       schema:
        minimum: 1
        maximum: 110000
        type: string
        format: binary
    responses:
     "201":
      description: CREATED
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/ImageInfo'
     "400":
      description: Bad Request
   get:
    security:
     - oauth2: [ ocx-up:all, ocx-up:read ]
    tags:
     - avatarInternal
    description: Get Image by id
    operationId: getImage
    parameters:
     - name: userId
       in: path
       required: true
       schema:
        type: string
     - name: refType
       required: true
       in: query
       schema:
        $ref: "#/components/schemas/RefType"
    responses:
     "200":
      description: OK
      content:
       image/*:
        schema:
         minimum: 1
         maximum: 110000
         type: string
         format: binary
     "400":
      description: Bad request
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/ProblemDetailResponse'
   delete:
    security:
     - oauth2: [ ocx-up:all, ocx-up:delete ]
    tags:
     - avatarInternal
    description: delete Image
    operationId: deleteImage
    parameters:
     - name: userId
       in: path
       required: true
       schema:
        type: string
    responses:
     "204":
      description: No Content
     "400":
      description: Bad request
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/avatar/me:
   post:
    security:
     - oauth2: [ ocx-up:all, ocx-up:write ]
    tags:
     - avatarInternal
    description: Upload Images
    parameters:
     - in: header
       name: Content-Length
       required: true
       schema:
        minimum: 1
        maximum: 110000
        type: integer
     - name: refType
       required: true
       in: query
       schema:
        $ref: "#/components/schemas/RefType"
    operationId: uploadMyImage
    requestBody:
     required: true
     content:
      image/*:
       schema:
        minimum: 1
        maximum: 110000
        type: string
        format: binary
    responses:
     "201":
      description: CREATED
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/ImageInfo'
     "400":
      description: Bad Request
   get:
    security:
     - oauth2: [ ocx-up:all, ocx-up:read ]
    tags:
     - avatarInternal
    description: Get Image by id
    operationId: getMyImage
    parameters:
     - name: refType
       required: true
       in: query
       schema:
        $ref: "#/components/schemas/RefType"
    responses:
     "200":
      description: OK
      content:
       image/*:
        schema:
         minimum: 1
         maximum: 110000
         type: string
         format: binary
     "400":
      description: Bad request
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/ProblemDetailResponse'
   delete:
    security:
     - oauth2: [ ocx-up:all, ocx-up:delete ]
    tags:
     - avatarInternal
    description: delete Image
    operationId: deleteMyImage
    responses:
     "204":
      description: No Content
     "400":
      description: Bad request
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/ProblemDetailResponse'
components:
 securitySchemes:
  oauth2:
   type: oauth2
   flows:
    clientCredentials:
     tokenUrl: https://oauth.simple.api/token
     scopes:
      ocx-up:all: Grants access to all operations
      ocx-up:read: Grants read access
      ocx-up:write: Grants write access
      ocx-up:delete: Grants access to delete operations
 schemas:
  RefType:
   type: string
   enum: [ small, medium, large ]
   default: 'medium'
  ImageInfo:
   type: object
   properties:
    id:
     type: string
  ProblemDetailResponse:
   type: object
   properties:
    errorCode:
     type: string
    detail:
     type: string
    params:
     type: array
     items:
      $ref: '#/components/schemas/ProblemDetailParam'
    invalidParams:
     type: array
     items:
      $ref: '#/components/schemas/ProblemDetailInvalidParam'
  ProblemDetailParam:
   type: object
   properties:
    key:
     type: string
    value:
     type: string
  ProblemDetailInvalidParam:
   type: object
   properties:
    name:
     type: string
    message:
     type: string